typography_spectrum: 0.06098
color:
  brandColors:
    - '#a39873'
    - '#4c4439'
    - '#c0721d'
    - '#347875'
    - '#df7baf'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.65671
analytics:
  google: null
  facebook: null
  twitter: null
name: toys
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
